### ISSUE TITLE
Uncaught Exception: ltmanage command not found

### ISSUE THREAD

**Issue by jackouille-ch** [jefs42/libretranslate#2]
Hi,
Here is the error I receive:
[Sun May 01 22:16:02.091599 2022] [proxy_fcgi:error] [pid 5246] [clientx.x.x.x:51112] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Exception: ltmanage command not found in /var/www/clients/client1/web70/web/vendor/jefs42/libretranslate/src/LibreTranslate.php:281\nStack trace:\n#0 /var/www/clients/client1/web70/web/jsc.php(10): Jefs42\\LibreTranslate->addKey()\n#1 {main}\n  thrown in /var/www/clients/client1/web70/web/vendor/jefs42/libretranslate/src/LibreTranslate.php on line 281'

Script used:
require('vendor/autoload.php');
use Jefs42\LibreTranslate;
$translator = new LibreTranslate("https://libretranslate.de",443, 'fr', 'en');
$translatedText = $translator->translate("Mon nom est Jacques");

In fact I'm searching a free solution to translate text from french to english, german and ukrainian for a website designed for helping ukrainian refugees. I can provide you the url via PM. I also tried to use libretranslate.com but it asks for an API key that I should pay, but I'm searching for a free solution...

And of course your class is installed:
ll vendor/
total 56
-rw-r--r-- 1 root root  178 Apr 25 18:47 autoload.php
drwxr-xr-x 2 root root 4096 Apr 25 18:47 bin
drwxr-xr-x 2 root root 4096 May  1 22:06 composer
drwxr-xr-x 3 root root 4096 Apr 25 18:47 firebase
drwxr-xr-x 9 root root 4096 Apr 25 18:47 google
drwxr-xr-x 3 root root 4096 Apr 25 18:47 grpc
drwxr-xr-x 5 root root 4096 Apr 25 18:47 guzzlehttp
drwxr-xr-x 3 root root 4096 May  1 22:06 jefs42
drwxr-xr-x 3 root root 4096 Apr 25 18:47 monolog
drwxr-xr-x 3 root root 4096 Apr 25 18:47 phpmailer
drwxr-xr-x 7 root root 4096 Apr 25 18:47 psr
drwxr-xr-x 3 root root 4096 Apr 25 18:47 ralouphie

What should I change to make it working ?

**Comment by jefs42** [comment]
Hello. Hope we can get you fixed up.

First off - a big thanks to you!  Testing your sample code I realized there was an error when setting default target language when creating the instance.  So you should do a composer update for that first: v1.1.1

In the traceback message of your error, it looks like you (at one point) were trying to addKey:
```bash
#0 /var/www/clients/client1/web70/web/jsc.php(10): Jefs42\LibreTranslate->addKey()
```
on line 10 of your jsc.php

But that's part of some ltmanage functions for if you are running the libretranslate on the same server to add/remove/list API keys for the server.

With the v1.1.1 target language fix (thanks again for that :) ) the code you posted above works fine for me (tested from a different server that also does not have the ltmanage program installed):
Input:
```php
<?php
require('vendor/autoload.php');
use Jefs42\LibreTranslate;
$translator = new LibreTranslate("https://libretranslate.de",443, 'fr', 'en');
$translatedText = $translator->translate("Mon nom est Jacques");

print "\n" .  $translatedText . "\n";
```
Output:
```bash
[jeff43@node1 translateTest]$ php test.php

My name is Jacques.
[jeff43@node1 translateTest]$
```

**Comment by jefs42** [comment]
Maybe at v2.0 I should rename the ltmanage related functions more specifically.

If you do need an API key for the server you want to use then that would be:
```php
$translator->setApiKey($apiKey);
```
and not the addKey($limit)
